version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  backend:
    build: .
    image: lexsense_app:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    command: uvicorn lexsense.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  frontend:
    image: lexsense_app:latest
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    command: streamlit run lexsense/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
